version: "3.7"

services:
  database:
    image: postgres:13
    container_name: fordva-database
    environment:
      POSTGRES_DB: ${APPSETTING_PGR_DB}
      POSTGRES_USER: ${APPSETTING_PGR_USER}
      POSTGRES_PASSWORD: ${APPSETTING_PGR_PASSWORD}
    ports:
      - ${APPSETTING_PGR_PORT}:5432
    volumes:
      - ${APPSETTING_DOCKER_DATA_FOLDER}/postgres:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      APPSETTING_PGADMIN_DEFAULT_EMAIL: ${APPSETTING_PGADMIN_DEFAULT_EMAIL}
      APPSETTING_PGADMIN_DEFAULT_PASSWORD: ${APPSETTING_PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${APPSETTING_PGADMIN_PORT}:80
    depends_on:
      - database
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
